version: '3'
services:
    monolith:
        image: monolith
        build: ./monolith

    humble-producer:
        image: humble-producer
        build: ./humble-generator

    product-consumer:
        image: product-consumer
        build: ./product-consumer

    origin-producer:
        image: origin-producer
        build: ./origin-generator
