version: '3'
services:
    humble-producer:
        image: humble-producer
        build: ./humble-producer

    origin-producer:
        image: origin-producer
        build: ./origin-producer

    product-consumer:
        image: product-consumer
        build: ./product-consumer
